package examples.ida.test;


import static org.junit.Assert.assertEquals;
import examples.ida.IdaOverseer;
import examples.ida.request.IdaConnectorParams;
import gov.usgs.cida.nude.params.OutputFormat;
import gov.usgs.cida.nude.provider.http.HttpProvider;
import gov.usgs.cida.nude.resultset.StringTableResultSet;
import gov.usgs.cida.nude.table.Column;
import gov.usgs.cida.nude.table.ColumnGrouping;
import gov.usgs.cida.nude.values.TableRow;

import java.io.StringWriter;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

public class IdaOverseerTest {

	public static HttpProvider httpProvider = new HttpProvider();
	
	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		httpProvider.init();
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
		httpProvider.destroy();
	}
	
	protected String expected = null;
	protected String actual = null;
	
	protected StringWriter sw = null;
	protected StringBuffer sbEx = null;
	
	@Before
	public void setUp() throws Exception {
		sw = new StringWriter();
		sbEx = new StringBuffer();
	}

	@After
	public void tearDown() throws Exception {
		expected = null;
		actual = null;
		
		sw = null;
		sbEx = null;
	}
	
	@Test
	public void testSomethingNew() throws Exception {
		
		IdaOverseer overseer = new IdaOverseer();
		
		String siteNumber = "04085427";
		
		overseer.addInput(buildXmlFormatParam());
		overseer.addInput(buildIdaParams(siteNumber));
		
		overseer.dispatch(sw);
		
		expected = getExpectedResponse();
		actual = sw.toString();
		
		assertEquals(expected, actual);
	}
	
	public static ResultSet buildXmlFormatParam() {
		ResultSet result = null;
		
		ColumnGrouping colGroup = new ColumnGrouping(OutputFormat.FORMAT_TYPE, Arrays.asList(new Column[] {OutputFormat.FORMAT_TYPE, OutputFormat.SCHEMA_TYPE}));
		StringTableResultSet params = new StringTableResultSet(colGroup);
		Map<Column, String> row = new HashMap<Column, String>();
		row.put(OutputFormat.FORMAT_TYPE, "XML");
		row.put(OutputFormat.SCHEMA_TYPE, "camelCase");
		TableRow tableRow = new TableRow(colGroup, row);
		params.addRow(tableRow);
		result = params;
		
		return result;
	}
	
	public static ResultSet buildIdaParams(String siteNo) {
		ResultSet result = null;
		
		List<Column> colList = new ArrayList<Column>();
		colList.addAll(Arrays.asList(IdaConnectorParams.values()));
		ColumnGrouping colGroup = new ColumnGrouping(IdaConnectorParams.SITE_NUMBER, colList);
		
		StringTableResultSet params = new StringTableResultSet(colGroup);
		
		Map<Column, String> row = new HashMap<Column, String>();
		row.put(IdaConnectorParams.GET_DATA, "true");
		row.put(IdaConnectorParams.SITE_NUMBER, siteNo);
		row.put(IdaConnectorParams.TO_DATE, "2010-08-30");
		row.put(IdaConnectorParams.FROM_DATE, "2010-08-30");
		
		TableRow tableRow = new TableRow(colGroup, row);
		params.addRow(tableRow);
		result = params;
		
		return result;
	}
	
	public static String getExpectedResponse() {
		StringBuilder result = new StringBuilder();
		
		result.append("<?xml version='1.0' encoding='UTF-8'?>");
		result.append("<success rowCount=\"-1\">");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830000000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"118");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830001500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830003000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830004500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830010000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830011500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"118");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830013000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830014500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830020000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"118");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830021500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830023000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830024500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830030000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830031500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830033000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830034500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830040000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830041500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830043000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830044500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830050000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830051500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830053000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830054500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830060000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830061500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830063000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"115");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830064500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830070000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"118");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830071500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830073000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"113");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830074500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830080000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830081500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830083000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830084500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830090000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830091500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830093000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830094500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830100000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830101500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830103000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830104500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830110000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830111500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830113000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830114500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830120000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"111");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830121500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830123000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830124500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830130000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830131500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830133000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830134500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830140000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830141500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"107");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830143000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830144500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830150000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830151500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830153000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830154500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830160000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830161500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830163000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830164500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830170000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830171500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830173000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830174500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"99");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830180000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830181500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830183000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"105");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830184500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830190000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830191500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830193000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830194500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830200000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"99");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830201500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830203000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830204500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830210000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830211500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830213000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830214500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830220000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830221500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830223000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830224500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"99");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830230000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830231500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"99");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830233000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"99");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100830234500");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"101");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append(	"<data>");
		result.append(		"<timestamp>");
		result.append(			"20100831000000");
		result.append(		"</timestamp>");
		result.append(		"<value>");
		result.append(			"103");
		result.append(		"</value>");
		result.append(	"</data>");
		result.append("</success>");
		
		return result.toString();
	}
}
